services:
  flashback:
    build: .
    container_name: flashback
    restart: unless-stopped
    environment:
      PORT: "4000"
    volumes:
      - ./volumes/games:/app/games
      - ./volumes/data:/app/data
      - ./volumes/ruffle:/app/public/ruffle
    ports:
      - "4000:4000"
